## Environment settings
defaults: &defaults
  api_version: v1
  host: https://facbot.herokuapp.com/
  port: 80
  protocol: http
  relative_url_root: /

  asset_host:
    enabled: false
    url: https://facbot.herokuapp.com/

  authentication:
    session_expiration_time: 86_400

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults